name: Auto Comment on PR Close

on:
    pull_request_target:
        types: [closed]

permissions:
    issues: write
    pull-requests: write

jobs:
    comment-on-close:
        runs-on: ubuntu-latest

        steps:
          - name: Add Comment to Closed PR
            run: |
              COMMENT=$(cat <<EOF
              {
                  "body": "🚀 Thank you for your contribution! This pull request has been closed. If you have any questions or need further assistance, feel free to reach out."
              }
              EOF
              )
              RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
                  -X POST \
                  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
                  -d "$COMMENT")
              cat response.json
              if [ "$RESPONSE" -ne 201 ]; then
                  echo "Failed to add comment on PR close"
                  exit 1
              fi
