name: Instructions Bot 

# Trigger the workflow on issue assignment
on:
  issues:
    types: [assigned]

jobs:
  add_pr_instructions:
    runs-on: ubuntu-latest

    steps:
      - name: Add a comment with PR instructions
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body": "### Instructions for Creating a Pull Request:\n\n1. Fork the repository if you haven\'t already.\n2. Create a new branch for your work: `git checkout -b feature-branch-name`.\n3. Make your changes in this branch.\n4. Commit your changes with a clear message: `git commit -m \"Describe your changes\"`.\n5. Push your branch to your forked repository: `git push origin feature-branch-name`.\n6. Go to the original repository and click on **New Pull Request**.\n7. Select your branch and submit the PR for review.\n8. Link the PR to this issue by adding the keyword **Closes #issue_number** in the PR description.\n\nThank you!"}'
